/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SsgiIndexRouteImport } from './routes/ssgi/index'
import { Route as ComputeShaderIndexRouteImport } from './routes/compute-shader/index'
import { Route as AtmosphereIndexRouteImport } from './routes/atmosphere/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SsgiIndexRoute = SsgiIndexRouteImport.update({
  id: '/ssgi/',
  path: '/ssgi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeShaderIndexRoute = ComputeShaderIndexRouteImport.update({
  id: '/compute-shader/',
  path: '/compute-shader/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtmosphereIndexRoute = AtmosphereIndexRouteImport.update({
  id: '/atmosphere/',
  path: '/atmosphere/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atmosphere': typeof AtmosphereIndexRoute
  '/compute-shader': typeof ComputeShaderIndexRoute
  '/ssgi': typeof SsgiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atmosphere': typeof AtmosphereIndexRoute
  '/compute-shader': typeof ComputeShaderIndexRoute
  '/ssgi': typeof SsgiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atmosphere/': typeof AtmosphereIndexRoute
  '/compute-shader/': typeof ComputeShaderIndexRoute
  '/ssgi/': typeof SsgiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atmosphere' | '/compute-shader' | '/ssgi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atmosphere' | '/compute-shader' | '/ssgi'
  id: '__root__' | '/' | '/atmosphere/' | '/compute-shader/' | '/ssgi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtmosphereIndexRoute: typeof AtmosphereIndexRoute
  ComputeShaderIndexRoute: typeof ComputeShaderIndexRoute
  SsgiIndexRoute: typeof SsgiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssgi/': {
      id: '/ssgi/'
      path: '/ssgi'
      fullPath: '/ssgi'
      preLoaderRoute: typeof SsgiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute-shader/': {
      id: '/compute-shader/'
      path: '/compute-shader'
      fullPath: '/compute-shader'
      preLoaderRoute: typeof ComputeShaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atmosphere/': {
      id: '/atmosphere/'
      path: '/atmosphere'
      fullPath: '/atmosphere'
      preLoaderRoute: typeof AtmosphereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtmosphereIndexRoute: AtmosphereIndexRoute,
  ComputeShaderIndexRoute: ComputeShaderIndexRoute,
  SsgiIndexRoute: SsgiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
